storeType: ONHEAP
threadCount: 33
entryCount: 20000000
offHeapSize: "20G"
maxOnHeapCount: 20000000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 3
updatePercentage: 10
diskStorePath: /tmp
