storeType: ONHEAP
threadCount: 33
entryCount: 300000000
offHeapSize: "0"
maxOnHeapCount: 300000000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 4
updatePercentage: 10
diskStorePath: /tmp
