storeType: OFFHEAP
threadCount: 33
entryCount: 20000000
offHeapSize: "20G"
maxOnHeapCount: 5000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 4
updatePercentage: 10
diskStorePath: java.io.tmpdir
monitoringEnabled: false
