storeType: ONHEAP
threadCount: 33
entryCount: 500000
offHeapSize: "0"
maxOnHeapCount: 500000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 40
updatePercentage: 10
diskStorePath: java.io.tmpdir
