storeType: OFFHEAP
threadCount: 33
entryCount: 500000
offHeapSize: "500M"
maxOnHeapCount: 5000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 40
updatePercentage: 10
diskStorePath: java.io.tmpdir
monitoringEnabled: false
useTerracottaArray: false
TerracottaArrayURL: localhost:9510
Consistency: eventual
monitoringEnabled: false
Concurrency: 0
nonStopCache: false
nonStopTimeoutMillis: 30000
nonStopTimeoutBehavior: localreads