storeType: OFFHEAP
threadCount: 33
entryCount: 10000000
offHeapSize: "10G"
maxOnHeapCount: 5000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 4
updatePercentage: 10
diskStorePath: java.io.tmpdir
monitoringEnabled: false
useTerracottaArray: false
TerracottaArrayURL: localhost:9510
Consistency: eventual