storeType: ONHEAP
threadCount: 33
entryCount: 0
offHeapSize: "0"
maxOnHeapCount: 0
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 40
updatePercentage: 10
diskStorePath: java.io.tmpdir
